import React, { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Session, FilmsMap } from "@/components/types";
import { generateSessionId } from "@/lib/utils"; // Import the function to generate session IDs

interface ImportModalProps {
  sessions: Session[];
  open: boolean;
  onClose: () => void;
  onImport: (sessions: Session[]) => void;
  filmsMap: FilmsMap;
}

// Modal to allow importing selected sessions
export function ImportModal({
  sessions,
  open,
  onClose,
  onImport,
  filmsMap,
}: ImportModalProps) {
  const [selectedSessions, setSelectedSessions] = useState<Set<string>>(
    new Set(),
  );

  // Toggle session selection using sessionId generated by generateSessionId
  const toggleSessionSelection = (sessionId: string) => {
    setSelectedSessions((prev) => {
      const updated = new Set(prev);
      if (updated.has(sessionId)) {
        updated.delete(sessionId);
      } else {
        updated.add(sessionId);
      }
      return updated;
    });
  };

  // Select all sessions using sessionId generated by generateSessionId
  const selectAllSessions = (isSelected?: boolean) => {
    if (isSelected) {
      setSelectedSessions(new Set(sessions.map((s) => generateSessionId(s))));
    } else {
      setSelectedSessions(new Set());
    }
  };

  // Handle importing the selected sessions based on sessionId
  const handleImport = () => {
    const selected = sessions.filter((session) =>
      selectedSessions.has(generateSessionId(session)),
    );
    onImport(selected);
    onClose(); // Close modal after import
  };

  return (
    <Dialog open={open}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Import Sessions</DialogTitle>
          <DialogDescription>
            The following sessions were found. Select the ones you&apos;d like
            to import.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-4">
          <div className="flex items-center sticky top-0">
            <Checkbox
              onCheckedChange={(checked) => selectAllSessions(Boolean(checked))}
              checked={selectedSessions.size === sessions.length}
            />
            <label className="ml-2">Select All</label>
          </div>

          <div className="max-h-[320px] overflow-auto">
            {sessions.map((session) => {
              const film = filmsMap.get(session.filmId);
              const sessionId = generateSessionId(session); // Generate the session ID
              if (!film) return null;

              return (
                <div key={sessionId} className="flex items-center space-x-2">
                  <Checkbox
                    onCheckedChange={() => toggleSessionSelection(sessionId)}
                    checked={selectedSessions.has(sessionId)}
                  />
                  <label>
                    {film.filmTitle} {session.location} -{" "}
                    {new Date(session.time).toLocaleString()}
                  </label>
                </div>
              );
            })}
          </div>
        </div>
        <DialogFooter>
          <Button variant="secondary" onClick={onClose}>
            Cancel
          </Button>
          <Button variant="default" onClick={handleImport}>
            Import Selected
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
